### ISSUE TITLE
Верстка и frontend-логика поста

### ISSUE THREAD

**Issue by Wayodeni** [ultrasonicdevs/lit_library#43]
1. Непонятный овал слева снизу вместо статуса
2. Огромное расстояние между превьюшкой книги и превьюшкой поста
3. Непонятно зачем превьюшка поста кликабельна (как ее закрывать - неочевидно)
4. Некликабельная книга (при клике не происходит никакого действия)
![bad_post](https://user-images.githubusercontent.com/68604828/196005605-eb602019-0b14-48a2-8e9d-a7a4ada5348a.gif)

**Comment by FoxyGDFD** [comment]
1. У тебя просто статус null и поэтому пусто -_-
2. Чекну
3. Кликабельность норм, закрыть так же как в ВК, могу конечно крестик докинуть но не вижу в нем смысла, когда можно тыкнуть по фону как и во всех формах
4. При клике должно переносить на страницу книги которой нет -_-
